swoole/library

- README.md
- composer.json
If coding standard violations can not be fixed automatically by PHP CS Fixer, this script can tell which PHP files to be fixed manually.
> add Composer script cs-check to check coding standard violations

- .php_cs.dist
- Dockerfile
- docker-compose.yml
- examples/fastcgi/proxy/README.md
- examples/fastcgi/proxy/base.php
- examples/fastcgi/proxy/wordpress.php
- src/core/Coroutine/FastCGI/Client.php
- src/core/Coroutine/FastCGI/Proxy.php
- src/core/FastCGI/HttpRequest.php
- src/core/FastCGI/HttpResponse.php
- src/core/FastCGI/Record/Params.php
Just:
```php
$proxy = new Proxy('php-fpm:9000', $documentRoot);
$server->on('request', function (Request $request, Response $response) use ($proxy) {
$proxy->pass($request, $response);
});
```
> Support FastCGI Proxy

- src/core/ConnectionPool.php
- tests/unit/Database/PDOPoolTest.php
when coroutine is enable:
```php
public function get()
{
if ($this->pool === null) {
throw new RuntimeException('Pool has been closed');
}
if ($this->pool->isEmpty() && $this->num < $this->size) {
$this->make();
}
return $this->pool->pop(); // <- coroutines which out of channel size will block here
}
```
put method just minus the num, but not create a new connection
```php
public function put($connection): void
{
if ($this->pool === null) {
return;
}
if ($connection !== null) {
$this->pool->push($connection);
} else {
/* connection broken */
$this->num -= 1;
}
}
```
so get method `$this->pool->pop()` will cause a dead lock
for this [issue](https://github.com/swoole/swoole-src/issues/2918) , coroutine will return directly without any exception
in the test case, result will contains 2 …
> fix ConnectionPool@put when error happens

- composer.json
- src/core/Database/MysqliProxy.php
- src/core/Database/MysqliStatementProxy.php
- src/core/Database/ObjectProxy.php
- src/core/Database/PDOProxy.php
- src/core/Database/PDOStatementProxy.php
- src/core/ObjectProxy.php
- tests/DatabaseTestCase.php
- tests/unit/Database/PDOStatementProxyTest.php
- tests/unit/ObjectProxyTest.php
In general database handle/connection objects shouldn't be cloneable. ([ref](https://bugs.php.net/bug.php?id=77849))
> Disable Cloning of Database Proxy Objects

- src/core/FastCGI/HttpResponse.php
Fix response header parsing when there is no space after the colon in the response header
fix unresolved:
```php
<?php
header('Content-Type:application/json');
```
> Fix response header parsing when there is no space after the colon in the response header

- phpunit.xml.dist
- src/core/FastCGI/HttpResponse.php
- tests/unit/FastCGI/HttpResponseTest.php
- tests/www/header2.php
- tests/www/status0.php
- tests/www/status1.php
- tests/www/status2.php
- tests/www/status3.php
This is to remove error control operators (the at sign) in class [\Swoole\FastCGI\HttpResponse](https://github.com/swoole/library/blob/master/src/core/FastCGI/HttpResponse.php).
> remove error control operators

- src/core/Database/PDOConfig.php
This option is misleading, because `postgresql` has not been coroutine, need to use [ext-postgresql](https://github.com/swoole/ext-postgresql)
> remove pgsql driver

- src/core/Curl/Handler.php
Should we add an error code and error message to get the reason for the error? 
For example, in this issue https://github.com/swoole/swoole-src/issues/3480
> fix: set error code and error message when execution fails

- src/core/Database/RedisPool.php
https://github.com/phpredis/phpredis/#parameters
```
reserved: should be NULL if retry_interval is specified
retry_interval: int, value in milliseconds (optional)
```
`array_filter` will filter out `reserved`
> fix: redis connect param

- src/core/Curl/Handler.php
- tests/unit/Curl/HandlerTest.php
```php
// composer require guzzlehttp/guzzle
include __DIR__ . '/vendor/autoload.php';
use GuzzleHttp\Client;
Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_ALL);
go(function () {
$url = 'https://httpbin.org/get';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
//    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_WRITEFUNCTION, function ($ch, $data) {
echo 'Data: ' . $data;
return strlen($data);
});
$data = curl_exec($ch);
curl_close($ch);
var_dump($data);
//
//    $client = new Client();
//    $url = 'http://baidu.com';
//    $res = $client->request('GET', $url);
//    var_dump($res->getBody()->getContents());
});
```
> Fix CURLOPT_WRITEFUNCTION

- src/core/Curl/Handler.php
As per RFC 2616 Section 4.2 HTTP headers should be case-insensitive. Some of the internal functions, such as `curl_setopt()` modify headers using their canonical name, such as `Content-Type`, `Cookie`, `Referer`, etc. However, using a canonical name might not always work properly, if the client has set a header name in the lower case, such as `content-type`, `referer` or upper case `CONTENT-TYPE`, `COOKIE` or any other mixture of letter casing. In order to fix this problem a new mapping beetwen the lower case header name representation and the actual header name is introduced and is now used when performing any header manipulations.
Fixes swoole/swoole-src#3850
> Handle cURL header names in case insensitive manner

- src/core/Coroutine/Barrier.php
the static property $cancel_list hold the value set in __destruct in some case.
after barrier object destructed by set it's reference by null, we can unset this that value added in __destruct 
the following test case could trigger this issue
```
/**
* Test without execution switching between coroutines.
*
* @covers \Swoole\Coroutine\Barrier
*/
public function testNoCoroutineSwitching()
{
run(function () {
$barrier = Barrier::make();
$count = 0;
$N = 4;
foreach (range(1, $N) as $i) {
\Swoole\Coroutine::create(function () use ($barrier, &$count) {
$count++;
});
}
Barrier::wait($barrier);
$this->assertSame($N, $count, 'The parent coroutine keeps running without switching execution to child coroutines.');
});
}
```
> fix Coroutine\Barrier mem leak

- composer.json
- src/core/ArrayObject.php
- tests/unit/ArrayObjectTest.php
Based on Rust's APIs like `map_or()` and `unwrap_or` this PR provides an alternative way for `get` that returns a default value, instead of throwing an exception, when the key does not exists.
> Add ArrayObject::getOr()

- src/core/StringObject.php
- tests/unit/MultibyteStringObjectTest.php
```
PHP Fatal error:  Declaration of Swoole\MultibyteStringObject::substr(int $offset, ?int $length = NULL, ?string $encoding = NULL) must be compatible with Swoole\StringObject::substr(int $offset, ?int $length = NULL): Swoole\StringObject in @swoole-src/library/core/MultibyteStringObject.php on line 64
```
> Fix substr error

- composer.json
- src/constants.php
- src/core/Curl/Handler.php
- src/ext/curl.php
- tests/unit/Curl/HandlerTest.php
Fix https://github.com/swoole/swoole-src/issues/4219
> Support CURLOPT_RESOLVE option for SWOOLE_HOOK_CURL

- src/core/Server/Admin.php
```
[2021-11-06 20:01:25 *13424.0]  ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught ErrorException: file_get_contents(/proc/0/status): failed to open stream: No such file or directory in @swoole-src/library/core/Server/Admin.php:1186
[2021-11-06 20:00:44 *11265.0]  ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught ErrorException: file_get_contents(/proc/0/stat): failed to open stream: No such file or directory in @swoole-src/library/core/Server/Admin.php:1156
```
> Fix error of get server memory and cpu usage in SWOOLE_BASE mode

- .github/workflows/syntax_checks.yml
`phplint` was removed from `jakzal/phpqa:php7.3` https://github.com/jakzal/toolbox/pull/398
This PR also drops `7.2` support as well.
Fixes CI error:
```
/entrypoint.sh: 6: exec: phplint: not found
Error: Process completed with exit code 127.
```
---
__This PR will neve be green because of #143__
> Removing old PHP versions from CI's style check step

- .github/workflows/unit_tests.yml
- README.md
- docker-compose.yml
It also fixes current documentation that says to run:
```bash
docker run --rm -v "$(pwd)":/var/www -t phpswoole/swoole:latest-dev composer update -n
```
But it actually fails because `phpswoole/swoole:latest-dev` doesn't have `ext-redis` which is required by the `composer.json` manifest file.
---
__This PR should wait #143 and #144 to be green__
> Refined Docker based development environment

- src/core/Database/PDOPool.php
If driver is 'pgsql', then 'charset' option must not be used else it gives fatal error.
Note: Database character set can be configured using "options" option.
> Do not use option 'charset', if driver is 'pgsql'

- src/core/Database/MysqliPool.php
$config 传来的charset并没有在constructor里被设置
> Fix set charset

- src/core/Database/DetectsLostConnections.php
Example fatal error trying to use database connection from PDOPool after a long time of not using them
```log
Fatal error: Uncaught ErrorException: PDOStatement::execute(): Send of 2109 bytes failed with errno=32 Broken pipe in @swoole/library/core/Database/PDOStatementProxy.php:53
Stack trace:
#0 [internal function]: Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}(8, 'PDOStatement::e...', '@swoole/library...', 53)
#1 @swoole/library/core/Database/PDOStatementProxy.php(53): PDOStatement->execute(Array)
#2 /home/dev/project/app/Tasks/SomethingTask.php(1921): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#3 [internal function]: App\Tasks\SomethingTask::batch('1', NULL, Array, 93, false)
#4 {main}
thrown in …
```
> Detect additional error message "Broken Pipe" as Lost Connection
