swoole/library

Dockerfile
README.md
docker-compose.yml
examples/bootstrap.php

This pull request is to use Docker to simplify local development environment.

Dockerize Local Development Environment

---

.gitignore
.travis.yml
Dockerfile
README.md
composer.json
docker-compose.yml
examples/bootstrap.php
phpunit.xml.dist
src/core/Database/PDOStatementProxy.php
tests/bootstrap.php
tests/unit/Database/PDOStatementProxyTest.php

This is to fix [issue #4](https://github.com/swoole/library/issues/4). The changes were made based on a previous pull request ([pull request #5](https://github.com/swoole/library/pull/5)).

Fix Issue 4: broken method call on class PDOStatement

---

src/core/Database/PDOStatementProxy.php

Fix https://github.com/swoole/library/issues/12

Fix setFetchMode missing arguments

---

.settings/org.eclipse.php.ui.prefs
src/core/Database/PDOConfig.php
src/core/Database/PDOPool.php

The driver is hard coded in **PDOPool** class:
https://github.com/swoole/library/blob/b62e0871910e951a20858adbcb8ea8b747274027/src/core/Database/PDOPool.php#L25
- `driver` in **PDOConfig** class
- set/get to `driver`
- constants for driver names
- `getAvailableDriver` to get the list of available drivers

add driver in PDOConfig

---

composer.json
examples/coroutine/batch.php
examples/coroutine/greeter.txt
src/core/Coroutine/functions.php

> v1: #3 
此封装较为常用, 关键的是保证了输入和输出的数组顺序一致

Add Coroutine\batch function

---

src/core/ConnectionPool.php

Fix ConnectionPool fill 

---

src/core/Curl/Handler.php

Support CURLOPT_FAILONERROR

---

src/core/Curl/Handler.php

* CURLOPT_SSLCERTTYPE
* CURLOPT_SSLCERT
* CURLOPT_SSLKEYTYPE
* CURLOPT_SSLKEY

Support Two-way SSL authentication

---

src/core/Database/MysqliPool.php

Fix mysqli options error

---

src/core/Curl/Handler.php

CURLOPT_POSTFIELDS可以设置为空来重置之前的post数据

chore: curl CURLOPT_POSTFIELDS

---

phpunit.xml.dist
src/core/Process/ProcessManager.php
tests/unit/FastCGI/HttpResponseTest.php
tests/unit/Process/ProcessManagerTest.php

the issue: https://github.com/swoole/swoole-src/issues/3392

feat:  add ProcessManager

---

src/core/Curl/Handler.php

Support CURLOPT_TCP_NODELAY

---

src/core/Coroutine/Barrier.php
tests/unit/Coroutine/BarrierTest.php

close #67
```bash
PHP Notice:  Undefined offset: 1 in @swoole-src/library/core/Coroutine/Barrier.php on line 30
PHP Warning:  Swoole\Coroutine::resume(): you can not resume the coroutine which is in IO operation or non-existent in @swoole-src/library/core/Coroutine/Barrier.php on line 36
```

Fix some errors in the barrier

---

src/core/Curl/Handler.php

Support Curl options

---

composer.json
src/core/Server/Helper.php
src/ext/sockets.php

Supported
------
Not supported
-----------------
- socket_​export_​stream
- socket_​import_​stream
- socket_​recvmsg
- socket_​sendmsg
- socket_​select
- socket_​addrinfo_​bind
- socket_​addrinfo_​connect
- socket_​addrinfo_​explain
- socket_​addrinfo_​lookup
- ~~socket_​wsaprotocol_​info_​export~~ (Windows Only)
- ~~socket_​wsaprotocol_​info_​import~~ (Windows Only)
- ~~socket_​wsaprotocol_​info_​release~~ (Windows Only)

Sockets hook

---

src/core/Curl/Handler.php

fix https://github.com/swoole/swoole-src/issues/4061

Fix the offset error caused by CURLOPT_PORT and CURLOPT_URL order

---

src/core/Coroutine/Http/functions.php
tests/unit/Coroutine/HttpFunctionTest.php

When using such as https://baidu.com

Fix Undefined index path

---

src/core/Coroutine/WaitGroup.php
tests/unit/Coroutine/WaitGroupTest.php

close https://github.com/swoole/swoole-src/issues/4089

Add count method to WaitGroup

---

.php_cs.dist
src/core/Coroutine/Http/functions.php

fix(issue/102): correct array to the client sets

---

src/core/Database/PDOProxy.php
src/core/Database/PDOStatementProxy.php

Not only error case would reach here, so, check it.

Fix swoole/swoole-src#4176

---

src/core/StringObject.php

Ps.: concatenation already does string conversion

Fix StringObject consistency between other methods and its immutability

---

src/core/Curl/Handler.php
src/ext/curl.php
tests/unit/Curl/HandlerTest.php

Fix https://github.com/swoole/swoole-src/issues/4287

Support CURLOPT_PRIVATE

---

src/core/Curl/Handler.php

Ignore CURLOPT_NOPROGRESS.
close https://github.com/swoole/swoole-src/issues/4334

Support CURLOPT_NOPROGRESS for SWOOLE_HOOK_CURL

---

src/core/Database/PDOStatementProxy.php
tests/unit/Database/PDOStatementProxyTest.php

Fix PDOStatement::bindParam() expects parameter 1 to be string

---

src/core/Server/Admin.php

usage
```php
$server->set([
'admin_server' => 'name:secret@0.0.0.0:9502',
]);
```

Add X-ADMIN-SERVER-ACCESS-TOKEN

---

src/core/ArrayObject.php

fix php 8.1 compatible

---

src/ext/sockets.php

It may return false when failure.
fix https://github.com/hyperf/hyperf/issues/4265

Fix return type of swoole_socket_send/write()

---

src/core/Database/PDOProxy.php
src/core/Database/PDOStatementProxy.php

Fix https://wenda.swoole.com/detail/108712

Fix PDO not thrown exception

---

src/core/ArrayObject.php
src/core/StringObject.php
tests/unit/ArrayObjectTest.php
tests/unit/StringObjectTest.php

Cleaner facades for object construction.
```php
use Swoole\StringObject as Str;
echo Str::from('Swoole Rocks')
->upper()
->append('!!!');
```

Add from static constructors

---

.github/workflows/unit_tests.yml
Dockerfile
tests/bootstrap.php

This is to fix broken CI jobs.

fix broken CI jobs
